### ISSUE TITLE
Staff online list

### ISSUE THREAD

**Issue by robert-beckley** [TreeboMC/TreeboTickets#1]
**Describe the bug**
The staff away tracker is not displayed in Hub server and its only shown in games server

**To Reproduce**
Join Hub see no list
Join games see list

**Expected behavior**
For the staff away list to display when joining hub server with correct perm node.
Not see it on any other server

**Screenshots**
![image](https://user-images.githubusercontent.com/41904721/55683811-5d29fa80-5987-11e9-86b4-fc6e5b9edf9a.png)

**Server Info (please complete the following information):**
Games
Hub

**Comment by ShakeforProtein** [comment]
This should be fixed in 2.2.0
