### ISSUE TITLE
Add "on hold" to ticket assign options on ticket page 

### ISSUE THREAD

**Issue by robert-beckley** [TreeboMC/TreeboTickets#2]
Remove Squishy and zarina and add  "on hold" as an option, also add the notify player option.

**Comment by ShakeforProtein** [comment]
On hold added to Web Interface. Notify player technically coded, will enable functionality in 2.2.1

**Comment by robert-beckley** [comment]
Plus remove mentioned staff. Dont know if chicken is in list but yeet him out
